# Copyright (c) 2025
# SPDX-License-Identifier: MIT

# ZMK Studio Support aktivieren
CONFIG_ZMK_STUDIO=y

# Speicherung der Einstellungen (Wichtig für BT Bonds & Studio)
CONFIG_SETTINGS=y
CONFIG_NVS=y
CONFIG_SETTINGS_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000

# Bluetooth Optimierungen
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# Encoder Support (falls benötigt)
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
