# Same image as ZMK upstream .github/workflows/build.yml (Zephyr 4.1 toolchain)
FROM docker.io/zmkfirmware/zmk-build-arm:4.1

# Set working directory
WORKDIR /workspaces

# Keep container running
CMD ["/bin/bash"]
