# Planckton Configuration
#
# ZMK Studio Support (Entsperrt & Optimiert)
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_RPC_THREAD_STACK_SIZE=4096

# Keyboard Identity
CONFIG_ZMK_KEYBOARD_NAME="Planckton"

# USB Stack configuration (Fix für Gerätename & Studio)
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="Planckton"
CONFIG_USB_DEVICE_MANUFACTURER="tf"
CONFIG_USB_DEVICE_VID=0x1D50
CONFIG_USB_DEVICE_PID=0x615E

# USB/BLE Features
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# Logging deaktivieren (Vermeidet CDC ACM Konflikte)
CONFIG_ZMK_USB_LOGGING=n

# Display deaktivieren (Vermeidet Konflikte mit Tipper TF)
CONFIG_ZMK_DISPLAY=n

# Batteriestandsanzeige
CONFIG_ZMK_BATTERY_REPORTING=y

# Deep Sleep nach 30 Minuten
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
